services:
  mysql:
    image: mysql:8
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=Notatnix
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - backnet

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    secrets:
      - db-password
    volumes:
      - ./backend/app:/var/www/app
    networks:
      - backnet
      - frontnet
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  proxy:
    image: nginx:1.23-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on: 
      - backend
    networks:
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet: